export const USERS_MOCK_DATA = [
  {
    id: 1,
    registrationDate: '2024-01-13',
    fullName: 'John Doe',
    position: 'Software Developer',
    email: 'john.doe@example.com',
    password: 'secretpassword',
    phoneNumber: '+1234567890',
  },
  {
    id: 2,
    registrationDate: '2024-01-13',
    fullName: 'Alice Smith',
    position: 'Data Scientist',
    email: 'alice.smith@example.com',
    password: 'secretpassword',
    phoneNumber: '+1987654321',
  },
  {
    id: 3,
    registrationDate: '2024-01-13',
    fullName: 'Bob Johnson',
    position: 'UX Designer',
    email: 'bob.johnson@example.com',
    password: 'secretpassword',
    phoneNumber: '+4455667788',
  },
  {
    id: 4,
    registrationDate: '2024-01-13',
    fullName: 'Emily Davis',
    position: 'Project Manager',
    email: 'emily.davis@example.com',
    password: 'secretpassword',
    phoneNumber: '+1122334455',
  },
  {
    id: 5,
    registrationDate: '2024-01-13',
    fullName: 'David Miller',
    position: 'Network Engineer',
    email: 'david.miller@example.com',
    password: 'secretpassword',
    phoneNumber: '+9988776655',
  },
  {
    id: 6,
    registrationDate: '2024-01-13',
    fullName: 'Sophia Turner',
    position: 'UI Developer',
    email: 'sophia.turner@example.com',
    password: 'secretpassword',
    phoneNumber: '+1123456789',
  },
  {
    id: 7,
    registrationDate: '2024-01-13',
    fullName: 'Daniel White',
    position: 'DevOps Engineer',
    email: 'daniel.white@example.com',
    password: 'secretpassword',
    phoneNumber: '+3344556677',
  },
  {
    id: 8,
    registrationDate: '2024-01-13',
    fullName: 'Olivia Brown',
    position: 'QA Tester',
    email: 'olivia.brown@example.com',
    password: 'secretpassword',
    phoneNumber: '+8899001122',
  },
  {
    id: 9,
    registrationDate: '2024-01-13',
    fullName: 'Michael Taylor',
    position: 'System Analyst',
    email: 'michael.taylor@example.com',
    password: 'secretpassword',
    phoneNumber: '+6677889900',
  },
  {
    id: 10,
    registrationDate: '2024-01-13',
    fullName: 'Grace Martinez',
    position: 'Business Analyst',
    email: 'grace.martinez@example.com',
    password: 'secretpassword',
    phoneNumber: '+1122334455',
  },
];
