export const USERS_MOCK_DATA = [
  {
    id: 1,
    registrationDate: '2023-12-10',
    fullName: 'John Doe',
    position: 'Software Developer',
    email: 'john.doe@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 800 555 35 35',
  },
  {
    id: 2,
    registrationDate: '2020-01-05',
    fullName: 'Alice Smith',
    position: 'Data Scientist',
    email: 'alice.smith@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 123 231 13 33',
  },
  {
    id: 3,
    registrationDate: '2019-06-07',
    fullName: 'Bob Johnson',
    position: 'UX Designer',
    email: 'bob.johnson@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 922 223 57 99',
  },
  {
    id: 4,
    registrationDate: '2024-01-13',
    fullName: 'Emily Davis',
    position: 'Project Manager',
    email: 'emily.davis@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 800 555 35 35',
  },
  {
    id: 5,
    registrationDate: '2024-01-13',
    fullName: 'David Miller',
    position: 'Network Engineer',
    email: 'david.miller@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 922 223 57 99',
  },
  {
    id: 6,
    registrationDate: '2024-01-13',
    fullName: 'Sophia Turner',
    position: 'UI Developer',
    email: 'sophia.turner@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 123 231 13 33',
  },
  {
    id: 7,
    registrationDate: '2024-01-13',
    fullName: 'Daniel White',
    position: 'DevOps Engineer',
    email: 'daniel.white@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 321 231 88 34',
  },
  {
    id: 8,
    registrationDate: '2024-01-13',
    fullName: 'Olivia Brown',
    position: 'QA Tester',
    email: 'olivia.brown@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 909 909 44 66',
  },
  {
    id: 9,
    registrationDate: '2024-01-13',
    fullName: 'Michael Taylor',
    position: 'System Analyst',
    email: 'michael.taylor@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 321 231 88 34',
  },
  {
    id: 10,
    registrationDate: '2024-01-13',
    fullName: 'Grace Martinez',
    position: 'Business Analyst',
    email: 'grace.martinez@example.com',
    password: 'secretpassword',
    phoneNumber: '+7 233 112 88 34',
  },
];
